# Generated by Django 3.0.7 on 2020-06-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='catid',
            field=models.IntegerField(),
        ),
    ]
