# Generated by Django 2.2.11 on 2020-06-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_auto_20200614_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
    ]
