# Generated by Django 3.0.7 on 2020-06-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.CharField(default='//', max_length=12),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
