# Generated by Django 3.0.7 on 2020-06-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200610_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.IntegerField(default=0),
        ),
    ]
