# Generated by Django 3.0.7 on 2020-06-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200612_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='cat_id',
            new_name='category_id',
        ),
    ]
