# Generated by Django 3.0.7 on 2020-06-15 13:45

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=martor.models.MartorField(),
        ),
    ]
