# Generated by Django 2.2.11 on 2020-06-22 16:33

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=martor.models.MartorField(),
        ),
    ]
