# Generated by Django 3.0.7 on 2020-06-16 11:27

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
