# Generated by Django 2.2.11 on 2020-06-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200615_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='body',
        ),
    ]
