# Generated by Django 2.2.11 on 2020-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200629_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='counting_cat_id',
            field=models.IntegerField(default=0),
        ),
    ]
