# Generated by Django 2.2.11 on 2020-06-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200624_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='newsTag',
        ),
    ]
