# Generated by Django 2.2.11 on 2020-06-18 15:27

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_news_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=martor.models.MartorField(default=''),
        ),
    ]
