# Generated by Django 2.2.11 on 2020-06-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_counting_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='counting_cat_id',
        ),
    ]
