# Generated by Django 2.2.11 on 2020-06-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news_count_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='count_category_id',
            new_name='count_cat_id',
        ),
    ]
