# Generated by Django 2.2.11 on 2020-07-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200630_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='count_cat_id',
            field=models.IntegerField(default=0),
        ),
    ]
