# Generated by Django 2.2.11 on 2020-06-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200610_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name_plural': 'Main Characteristics'},
        ),
    ]
